// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';
import {fansly} from '../models';

export function BrowseForFile(arg1:string,arg2:string):Promise<string>;

export function BrowseForFolder(arg1:string):Promise<string>;

export function CreateClip(arg1:number,arg2:number,arg3:string):Promise<services.ClipResult>;

export function GetAllChatMessages():Promise<Array<models.ChatMessage>>;

export function GetClips():Promise<Array<string>>;

export function GetCurrentClipsDir():Promise<string>;

export function GetFanslyConfig():Promise<fansly.Config>;

export function GetFanslyStreams():Promise<fansly.StreamsResult>;

export function GetMessagesAtTime(arg1:number,arg2:number):Promise<Array<models.ChatMessage>>;

export function GetVideoFileInfo():Promise<Record<string, string>>;

export function LoadChatFromPath(arg1:string):Promise<string>;

export function LoadFanslyStream(arg1:string):Promise<fansly.StreamResult>;

export function LoadVideoFromPath(arg1:string):Promise<string>;

export function OpenChatFile(arg1:Array<string>):Promise<string>;

export function OpenClipsFolder():Promise<void>;

export function OpenVideoFile():Promise<string>;

export function SaveFanslyConfig(arg1:fansly.Config):Promise<void>;

export function SetClipStorageOption(arg1:string,arg2:string):Promise<void>;
