// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForFile(arg1, arg2) {
  return window['go']['main']['App']['BrowseForFile'](arg1, arg2);
}

export function BrowseForFolder(arg1) {
  return window['go']['main']['App']['BrowseForFolder'](arg1);
}

export function CreateClip(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateClip'](arg1, arg2, arg3);
}

export function GetAllChatMessages() {
  return window['go']['main']['App']['GetAllChatMessages']();
}

export function GetClips() {
  return window['go']['main']['App']['GetClips']();
}

export function GetCurrentClipsDir() {
  return window['go']['main']['App']['GetCurrentClipsDir']();
}

export function GetFanslyConfig() {
  return window['go']['main']['App']['GetFanslyConfig']();
}

export function GetFanslyStreams() {
  return window['go']['main']['App']['GetFanslyStreams']();
}

export function GetMessagesAtTime(arg1, arg2) {
  return window['go']['main']['App']['GetMessagesAtTime'](arg1, arg2);
}

export function GetVideoFileInfo() {
  return window['go']['main']['App']['GetVideoFileInfo']();
}

export function LoadChatFromPath(arg1) {
  return window['go']['main']['App']['LoadChatFromPath'](arg1);
}

export function LoadFanslyStream(arg1) {
  return window['go']['main']['App']['LoadFanslyStream'](arg1);
}

export function LoadVideoFromPath(arg1) {
  return window['go']['main']['App']['LoadVideoFromPath'](arg1);
}

export function OpenChatFile(arg1) {
  return window['go']['main']['App']['OpenChatFile'](arg1);
}

export function OpenClipsFolder() {
  return window['go']['main']['App']['OpenClipsFolder']();
}

export function OpenVideoFile() {
  return window['go']['main']['App']['OpenVideoFile']();
}

export function SaveFanslyConfig(arg1) {
  return window['go']['main']['App']['SaveFanslyConfig'](arg1);
}

export function SetClipStorageOption(arg1, arg2) {
  return window['go']['main']['App']['SetClipStorageOption'](arg1, arg2);
}
