name: Wails build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'  # Run on any tag for releases

jobs:
  build-linux-windows:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: ArchivePlayer, platform: linux/amd64, os: ubuntu-latest},
          {name: ArchivePlayer, platform: windows/amd64, os: windows-latest},
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Install Linux dependencies
        if: matrix.build.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1 \
            pkg-config \
            build-essential \
            ffmpeg  # Required for clip creation feature
            
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'  # Match your local Go version
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      # Install Wails
      - name: Install Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails doctor
          
      # Build the application
      - name: Build Wails app
        run: |
name: Wails build

on:
  push:
    tags:
      - '*'  # Run on any tag for releases

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      # Install Wails
      - name: Install Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails doctor
          
      # Build the application
      - name: Build Wails app
        run: |
          wails build -platform windows/amd64 -webview2 download
          
      # Upload artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: ArchivePlayer-windows
          path: ./build/bin/
          
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            pkg-config \
            build-essential \
            ffmpeg
            
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      # Install Wails
      - name: Install Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails doctor
          
      # Build the application with webkit2_41 tag
      - name: Build Wails app
        run: |
          wails build -platform linux/amd64 -tags webkit2_41
          
      # Upload artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: ArchivePlayer-linux
          path: ./build/bin/
          
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      # Install FFmpeg for clip creation feature
      - name: Install FFmpeg
        run: brew install ffmpeg
          
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
        
      - name: Build app
        run: |
          wails build --platform darwin/universal
          
      - name: Package macOS app
        run: |
          # Create zip archive of the app
          cd ./build/bin/
          # Use the correct app name from the build output
          ditto -c -k --keepParent FanslyArchivePlayer.app FanslyArchivePlayer.app.zip
          
          # Create installer package
          productbuild --component FanslyArchivePlayer.app FanslyArchivePlayer.pkg
          
      - uses: actions/upload-artifact@v4
        with:
          name: ArchivePlayer-macos
          path: ./build/bin/
          
  create-release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/ArchivePlayer-windows/*
            artifacts/ArchivePlayer-linux/*
            artifacts/ArchivePlayer-macos/*
          draft: false
          prerelease: false

