name: Wails build

on:
  push:
    tags:
      - '*'  # Run on any tag for releases

jobs:
  build-linux-windows:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: ArchivePlayer, platform: linux/amd64, os: ubuntu-latest},
          {name: ArchivePlayer, platform: windows/amd64, os: windows-latest},
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Install Linux dependencies
        if: matrix.build.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1 \
            pkg-config \
            build-essential \
            ffmpeg  # Required for clip creation feature
            
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'  # Match your local Go version
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      # Install Wails
      - name: Install Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails doctor
          
      # Build the application
      - name: Build Wails app
        run: |
          wails build -platform ${{ matrix.build.platform }} -webview2 download
          
      # Upload artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: ArchivePlayer-${{ matrix.build.os }}
          path: ./build/bin/
          
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'  # Match your local Go version
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      # Install FFmpeg for clip creation feature
      - name: Install FFmpeg
        run: brew install ffmpeg
          
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
        
      - name: Install macOS build dependencies
        run: brew install nsis
        
      - name: Build app
        run: |
          wails build --platform darwin/universal -webview2 download
          ditto -c -k ./build/bin/ArchivePlayer.app ./build/bin/ArchivePlayer.app.zip
          
      - name: Building Installer
        run: |
          productbuild --component ./build/bin/ArchivePlayer.app ./build/bin/ArchivePlayer.pkg
          
      - uses: actions/upload-artifact@v4
        with:
          name: ArchivePlayer-macos
          path: ./build/bin/
          
  create-release:
    needs: [build-linux-windows, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/ArchivePlayer-ubuntu-latest/*
            artifacts/ArchivePlayer-windows-latest/*
            artifacts/ArchivePlayer-macos/*
          draft: false
          prerelease: false

