name: Wails build

on:
  push:
    tags:
    # Match any new tag
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: ArchivePlayer, platform: linux/amd64, os: ubuntu-latest},
          {name: ArchivePlayer, platform: windows/amd64, os: windows-latest},
          {name: ArchivePlayer, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      # Set up Go with the same version as your local development
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
          
      # Install the correct version of garble
      - name: Install garble
        run: go install mvdan.cc/garble@latest
        
      # Use the wails-build-action with specified version
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          build-obfuscate: true
          wails-version: "v2.9.0"
          go-version: "1.24.2"
